version: '3.2'

services:
  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: plutus
      POSTGRES_USER: plutus
      POSTGRES_DB: plutus

  caddy:
    image: "abiosoft/caddy:latest"
    volumes:
      - /mnt/$PWD/ssl:/root/certs # to sync mkcert certificates to Caddy
      - /mnt/$PWD/Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "2015:2015"


